-- 게시판 테이블 생성 및 코맨트
CREATE TABLE TB_BOARD ( 
        IDX NUMBER PRIMARY KEY,
        PARENT_IDX NUMBER, 
        TITLE VARCHAR2(100) NOT NULL, 
        CONTENTS VARCHAR2(4000) NOT NULL, 
        HIT_CNT NUMBER NOT NULL, 
        DEL_GB VARCHAR2(1) DEFAULT 'N' NOT NULL, 
        CREA_DTM DATE DEFAULT SYSDATE NOT NULL, 
        CREA_ID VARCHAR2(30) NOT NULL 
        ); 
COMMENT ON TABLE TB_BOARD IS '게시판'; COMMENT ON COLUMN TB_BOARD.IDX IS '인덱스'; COMMENT ON COLUMN TB_BOARD.PARENT_IDX IS '부모글 인덱스'; COMMENT ON COLUMN TB_BOARD.TITLE IS '제목'; COMMENT ON COLUMN TB_BOARD.CONTENTS IS '내용'; COMMENT ON COLUMN TB_BOARD.HIT_CNT IS '조회수'; COMMENT ON COLUMN TB_BOARD.DEL_GB IS '삭제구분'; COMMENT ON COLUMN TB_BOARD.CREA_DTM IS '생성일자'; COMMENT ON COLUMN TB_BOARD.CREA_ID IS '생성자 ID';
        
CREATE SEQUENCE SEQ_TB_BOARD_IDX START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
        
commit;

-- 회원 테이블

CREATE TABLE TB_USER(
    USER_ID VARCHAR(50) NOT NULL,
    USER_PW VARCHAR(100) NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(50) NOT NULL,
    USER_POINT INT NOT NULL,
    SESSION_KEY VARCHAR(50) NOT NULL,
    SESSION_LIMIT TIMESTAMP,
    USER_IMG VARCHAR(100) NOT NULL,
    USER_JOIN_DATE TIMESTAMP NOT NULL,
    USER_LOGIN_DATE TIMESTAMP NOT NULL, 
    USER_SIGNATURE VARCHAR(200) NOT NULL,
    PRIMARY KEY (USER_ID)
);

-- 테이블 alter dafault 설정
-- USER_POINT DEFAULT:0 , SESSION_KEY DEFAULT 'none', USER_IMG DEFAULT 'user/default-user.png', USER_JOIN_DATE NOW(), USER_LOGIN_DATE NOW(), USER_SIGNATURE DEFAULT '안녕하세요 ^^'
ALTER TABLE TB_USER MODIFY (USER_POINT DEFAULT 0);
ALTER TABLE TB_USER MODIFY (SESSION_KEY DEFAULT 'none');
ALTER TABLE TB_USER MODIFY (USER_IMG DEFAULT 'user/default-user.png');
ALTER TABLE TB_USER MODIFY (USER_JOIN_DATE DEFAULT sysdate);
ALTER TABLE TB_USER MODIFY (USER_LOGIN_DATE DEFAULT sysdate);
ALTER TABLE TB_USER MODIFY (USER_SIGNATURE DEFAULT '안녕하세요 ^^');

COMMIT;

insert into tb_user(
    USER_ID,
    USER_PW,
    USER_NAME,
    USER_EMAIL
)VALUES(
    'admin',
    123,
    'admin',
    'admin@first.com'
);

select * from tb_board;
SELECT * FROM tb_user;

-- 로그인 체크 쿼리
SELECT 
      USER_ID      
FROM TB_USER
    WHERE USER_ID = 'admin'
    and   USER_PW = '123';
      
      








